<?php

/**
 * @file
 * Contains oc_field2paras.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oc_field2para_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oc_field2paras module.
    case 'help.page.oc_field2para':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Takes oc_doc fields, creates paras and adds fields as embeded etc.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function oc_field2para_theme() {
  return [
    'oc_field2paras' => [
      'render element' => 'children',
    ],
  ];
}


