<?php

/**
 * @file
 * Contains oc_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ocblock_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oc_content module.
    case 'help.page.oc_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo content for Opencat') . '</p>';
      return $output;

    default:
  }
}
